name: Run integration tests
on: [workflow_dispatch]
jobs:
  build:
    name: Build toolbox
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        release: [R2022b, R2023a, R2023b, R2024a]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
          release: ${{matrix.release}}
      - name: Run tests
        uses: matlab-actions/run-tests@v2
